### ISSUE TITLE
Problem with AMC natural players

### ISSUE THREAD

**Issue by PixelMAA** [moth1995/pes_stats_converter_copy_addon#1]
Hi! Whenever i try to copy the stats of a player from fminside with AMC as his natural position it doesn't really copy the stats. This doesn't happen with players which AMC is their secondary position. Thank you very much in advance.

**Comment by moth1995** [comment]
Hi, can you send me some links of players on which this issue happens? are you using the latest version?

**Comment by PixelMAA** [comment]
Hello again! Yes, i'm using the latest version on chrome. Here are some players which their stats don't copy:

https://fminside.net/players/4-fm-24/76002390-james-rodriguez
https://fminside.net/players/4-fm-24/2000225781-thiago-perugini
https://fminside.net/players/4-fm-24/2000107899-matias-gomez
https://fminside.net/players/4-fm-24/96132920-jakub-kauziski

**Comment by PixelMAA** [comment]
Ah, i forgot to tell this only happens when i try to copy the stats for pes 2021.

**Comment by moth1995** [comment]
thanks for the report and the examples, im gonna try to fix it on the following days

**Comment by moth1995** [comment]
thanks for the report, fixed on [#4ccf75d0dbde18594ef1813e66e402e8c47bf61f](https://github.com/moth1995/pes_stats_converter_copy_addon/commit/4ccf75d0dbde18594ef1813e66e402e8c47bf61f)
