### ISSUE TITLE
not working on sofifa website

### ISSUE THREAD

**Issue by Lukasob95** [moth1995/pes_stats_converter_copy_addon#3]
after update 1.3.1 it is not working on the sofifa website in pes 2013.

**Comment by moth1995** [comment]
Sorry but for pes2013 it was only from fminside it never worked for sofifa

**Comment by Lukasob95** [comment]
I switched to version 1.2.8 and sofifa for pes 2013 is working, it always worked for me.

**Comment by Lukasob95** [comment]
> Sorry but for pes2013 it was only from fminside it never worked for sofifa

Ohh...true. I looked again correctly and it only works on fminside. Thanks for the answer!

**Comment by moth1995** [comment]
You might have been getting pes5 stats, sooner i will implement it someone is sharing some formulas for sofifa and also pesmaster

**Comment by Lukasob95** [comment]
Thank you for the performance of updating  stats pes 2013 for sofifa site. 
I'm testing it and it's actually working now for pes 2013.
